name: Node CI/CD workflow

on: [push]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: |
        docker build . -t yassinesayadi/pe-frontend:latest
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker push
      run: |
        docker push yassinesayadi/pe-frontend:latest

    - name: Sent post request to Portainer Service Webhook
      uses: jasongitmail/fast-webhook@v1
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        data: '{}'
      